### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by jbailey** [dynamo/dynamo#186]
I'm trying to update/compile dynamo and getting the following error.  I'm running elixir 0.12.3-dev

```
== Compilation error on file lib/dynamo/cowboy/connection.ex ==
could not compile dependency dynamo, mix compile failed. You can recompile this dependency with `mix deps.compile dynamo` or update it with `mix deps.update dynamo`
** (CompileError) lib/dynamo/cowboy/connection.ex:106: function '<-'/2 undefined
    (stdlib) lists.erl:1323: :lists.foreach/2
    lib/dynamo/cowboy/connection.ex:1: (file)
    (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
    (elixir) lib/kernel/parallel_compiler.ex:91: Kernel.ParallelCompiler."-spawn_compilers/8-fun-0-"/3
```

**Comment by saponinsky** [comment]
Looks like it was fixed literally 5 minutes after you posted this: https://github.com/dynamo/dynamo/commit/f145e7a2d06e75697da49d78fdd76f114e1e7e13
