### ISSUE TITLE
Error OSX (home-brew): mix deps.compile mime 

### ISSUE THREAD

**Issue by evan108108** [dynamo/dynamo#195]
I can't seem to get `MIX_ENV=test mix do deps.get, test` to work.

Elixir 0.12.2

Erlang R16B03 (erts-5.10.4) [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Eshell V5.10.4  (abort with ^G)

``` bash
$ mix deps.compile mime
* Compiling mime
Compiled lib/mime.ex
== Compilation error on file lib/mime/types.ex ==
could not compile dependency mime, mix compile failed. You can recompile this dependency with `mix deps.compile mime` or update it with `mix deps.update mime`
** (UndefinedFunctionError) undefined function: String.match?/2
    (elixir) String.match?("# This is a comment. I love comments.\t\t    -*- indent-tabs-mode: t -*-\n", %r"^[#\n]")
    lib/mime/types.ex:10: :elixir_compiler_1."-__MODULE__/1-fun-0-"/2
    (elixir) lib/enum.ex:1139: Enum."-reduce/3-fun-0-"/3
    (elixir) lib/stream.ex:994: Stream.do_resource/5
    (elixir) lib/enum.ex:1138: Enum.reduce/3
    lib/mime/types.ex:9: (module)
```

**Comment by devinus** [comment]
What branch of dynamo are you using?

**Comment by evan108108** [comment]
Master

**Comment by devinus** [comment]
@evan108108 master branch of Dynamo only works on masters versions of Elixir, try using the elixir-0.12.2 tag of dynamo.

**Comment by evan108108** [comment]
@devinus I checked out tag: elixir-0.12.2 and ran the same steps again and again I get the same error. :(

**Comment by devinus** [comment]
@evan108108 The mime dependency didn't exist in the elixir-0.12.2 tag, can you try again?

**Comment by lau** [comment]
I have the same problem. @devinus does this mean that dynamo is not compatible with Elixir 12.2?
Even if I checkout the elixir-0.12.2 tag, when using "mix dynamo projectname" and then "mix deps.get" in the new proejct I get the same error. I assume this is because the new project has dynamo listed as a dependency from github without a tag specified. If I add tag "elixir-0.12.2" to mix.exs in the new project it still does not work.

Is there any support for using elixir-0.12.2 at all?

**Comment by devinus** [comment]
@evan108108 Remember to redo `mix deps.get` and `mix compile` when you checkout the tag.

**Comment by evan108108** [comment]
@devinus I deleted my local dynamo repo and started fresh. I am still getting the same error. Here is my complete terminal session.

``` terminal
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir$ git clone git@github.com:dynamo/dynamo.git
Cloning into 'dynamo'...
remote: Reusing existing pack: 5750, done.
remote: Counting objects: 60, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 5810 (delta 9), reused 0 (delta 0)
Receiving objects: 100% (5810/5810), 1.29 MiB | 393.00 KiB/s, done.
Resolving deltas: 100% (2323/2323), done.
Checking connectivity... done.
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:55:31
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir$ cd dynamo/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:55:34
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamo$ git tag
elixir-0.10.0
elixir-0.10.1
elixir-0.10.2
elixir-0.11.1
elixir-0.11.2
elixir-0.12.0
elixir-0.12.1
elixir-0.12.2
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:55:37
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamo$ git checkout elixir-0.12.2
Note: checking out 'elixir-0.12.2'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

HEAD is now at 3141f40... Merge pull request #164 from CurveBeryl/master
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:55:46
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamo$ MIX_ENV=test mix do deps.get, test
* Getting mimetypes (git://github.com/spawngrid/mimetypes.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/mimetypes'...
remote: Reusing existing pack: 189, done.
remote: Total 189 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (189/189), 150.75 KiB | 0 bytes/s, done.
Resolving deltas: 100% (93/93), done.
Checking connectivity... done.
* Getting cowboy (git://github.com/extend/cowboy.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/cowboy'...
remote: Reusing existing pack: 5759, done.
remote: Total 5759 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (5759/5759), 3.52 MiB | 710.00 KiB/s, done.
Resolving deltas: 100% (3338/3338), done.
Checking connectivity... done.
* Getting hackney (git://github.com/benoitc/hackney.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/hackney'...
remote: Reusing existing pack: 2024, done.
remote: Total 2024 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (2024/2024), 811.36 KiB | 723.00 KiB/s, done.
Resolving deltas: 100% (1307/1307), done.
Checking connectivity... done.
* Getting hackney_lib (https://github.com/benoitc/hackney_lib.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/hackney_lib'...
remote: Reusing existing pack: 1018, done.
remote: Total 1018 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (1018/1018), 361.31 KiB | 665.00 KiB/s, done.
Resolving deltas: 100% (611/611), done.
Checking connectivity... done.
* Getting cowlib (git://github.com/extend/cowlib.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/cowlib'...
remote: Reusing existing pack: 78, done.
remote: Total 78 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (78/78), 51.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (39/39), done.
Checking connectivity... done.
* Getting ranch (git://github.com/extend/ranch.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamo/deps/ranch'...
remote: Reusing existing pack: 799, done.
remote: Total 799 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (799/799), 253.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (461/461), done.
Checking connectivity... done.
* Compiling mimetypes
==> mimetypes (compile)
Compiled src/mimetypes_scan.xrl
Compiled src/mimetypes_parse.yrl
Compiled src/mimetypes_app.erl
Compiled src/mimetypes_loader.erl
Compiled src/mimetypes.erl
Compiled src/mimetypes_sup.erl
Compiled src/mimetypes_parse.erl
Compiled src/mimetypes_scan.erl
* Compiling hackney_lib
==> hackney_lib (compile)
Compiled src/hackney_cookie.erl
Compiled src/hackney_bstr.erl
Compiled src/hackney_date.erl
Compiled src/hackney_http.erl
Compiled src/hackney_multipart.erl
Compiled src/hackney_headers.erl
Compiled src/hackney_url.erl
* Compiling ranch
==> ranch (compile)
Compiled src/ranch_protocol.erl
Compiled src/ranch_transport.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_app.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_ssl.erl
* Compiling hackney
==> hackney (compile)
Compiled src/hackney_pool_handler.erl
Compiled src/hackney_app.erl
Compiled src/hackney_deps.erl
Compiled src/hackney_http_proxy.erl
Compiled src/hackney_connect.erl
Compiled src/hackney_manager.erl
Compiled src/hackney_pool.erl
Compiled src/hackney.erl
Compiled src/hackney_socks5.erl
Compiled src/hackney_ssl_transport.erl
Compiled src/hackney_response.erl
Compiled src/hackney_sup.erl
Compiled src/hackney_request.erl
Compiled src/hackney_tcp_transport.erl
Compiled src/hackney_util.erl
Compiled src/hackney_stream.erl
* Compiling cowlib
==> cowlib (compile)
Compiled src/cow_cookie.erl
Compiled src/cow_http.erl
Compiled src/cow_date.erl
Compiled src/cow_qs.erl
Compiled src/cow_spdy.erl
Compiled src/cow_mimetypes.erl
* Compiling cowboy
==> cowboy (compile)
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_client.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy_multipart.erl
Compiled src/cowboy_protocol.erl
Compiled src/cowboy_http.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_req.erl
Compiled src/cowboy_websocket.erl
Compiled lib/dynamo/app.ex
Compiled lib/dynamo/base.ex
Compiled lib/dynamo/connection/behaviour.ex
Compiled lib/dynamo/cowboy/handler.ex
Compiled lib/dynamo/connection/query_parser.ex
Compiled lib/dynamo/cowboy.ex
Compiled lib/dynamo/connection/utils.ex
Compiled lib/dynamo.ex
Compiled lib/dynamo/filters/exceptions/public.ex
Compiled lib/dynamo/filters/head.ex
Compiled lib/binary/dict.ex
Compiled lib/dynamo/filters/loader.ex
Compiled lib/dynamo/filters/methodoverride.ex
Compiled lib/dynamo/helpers.ex
Compiled lib/dynamo/filters/static.ex
Compiled lib/dynamo/helpers/content_for.ex
Compiled lib/dynamo/helpers/escaping.ex
Compiled lib/dynamo/http.ex
Compiled lib/dynamo/helpers/render.ex
Compiled lib/dynamo/filters/session/stores.ex
Compiled lib/dynamo/http/cookies.ex
Compiled lib/dynamo/http/halt.ex
Compiled lib/dynamo/filters/session.ex
Compiled lib/dynamo/cowboy/body_parser.ex
Compiled lib/dynamo/http/redirect.ex
Compiled lib/dynamo/http/case.ex
Compiled lib/dynamo/http/session.ex
Compiled lib/dynamo/http/render.ex
Compiled lib/dynamo/exceptions.ex
Compiled lib/dynamo/http/hibernate.ex
Compiled lib/dynamo/router.ex
Compiled lib/dynamo/loader/error_handler.ex
Compiled lib/dynamo/supervisor.ex
Compiled lib/dynamo/router/filters.ex
Compiled lib/dynamo/router/utils.ex
Compiled lib/dynamo/filters/exceptions/debug.ex
Compiled lib/dynamo/static.ex
Compiled lib/dynamo/loader.ex
Compiled lib/dynamo/connection.ex
Compiled lib/dynamo/filters/exceptions.ex
Compiled lib/dynamo/templates/handler.ex
Compiled lib/dynamo/utils/message_verifier.ex
Compiled lib/dynamo/utils/once.ex
Compiled lib/dynamo/templates/finder.ex
Compiled lib/dynamo/templates/renderer.ex
Compiled lib/mix/tasks/dynamo.filters.ex
Compiled lib/mix/tasks/compile.dynamo.ex
Compiled lib/dynamo/templates.ex
Compiled lib/mix/tasks/server.ex
Compiled lib/dynamo/router/base.ex
Compiled lib/dynamo/cowboy/connection.ex
Compiled lib/mix/tasks/dynamo.ex
Compiled lib/dynamo/connection/test.ex
Generated dynamo.app
...................................................................................................................................................................
=ERROR REPORT==== 3-Feb-2014::09:56:52 ===
      Conn: GET /other
    Reason: (Dynamo.NotFoundError) no route found
Stacktrace:
  test/dynamo/cowboy/router_test.exs:4: Dynamo.Cowboy.RouterTest.RouterApp.dispatch/3
  (dynamo) lib/dynamo/filters/exceptions.ex:14: Dynamo.Filters.Exceptions.service/3
  (dynamo) lib/dynamo/cowboy/handler.ex:14: Dynamo.Cowboy.Handler.init/3
  (cowboy) src/cowboy_handler.erl:69: :cowboy_handler.handler_init/4
  (cowboy) src/cowboy_protocol.erl:529: :cowboy_protocol.execute/4
...................................................................................

Finished in 7.2 seconds (1.9s on load, 5.3s on tests)
246 tests, 0 failures
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:56:58
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamo$ mix dynamo /Users/evan.frolich/Sites/elixir/dynamoApp
* creating README.md
* creating .gitignore
* creating mix.lock
* creating mix.exs
* creating web
* creating web/routers
* creating web/routers/application_router.ex
* creating web/templates
* creating web/templates/index.html.eex
* creating lib
* creating lib/dynamo_app.ex
* creating lib/dynamo_app
* creating lib/dynamo_app/dynamo.ex
* creating lib/dynamo_app/environments
* creating lib/dynamo_app/environments/dev.exs
* creating lib/dynamo_app/environments/test.exs
* creating lib/dynamo_app/environments/prod.exs
* creating priv
* creating priv/static
* creating priv/static/favicon.ico
* creating test
* creating test/test_helper.exs
* creating test/features
* creating test/features/home_test.exs
* creating test/routers
* creating test/routers/application_router_test.exs
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:57:46
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamo$ cd ../dynamoApp/
------------------------------------------------------------------------------------------------------------------------------------------------------------------------- 09:58:07
evan.frolich@Controls-MacBook-Pro-3:~/Sites/elixir/dynamoApp$ mix deps.get
* Getting cowboy (git://github.com/extend/cowboy.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamoApp/deps/cowboy'...
remote: Reusing existing pack: 5759, done.
remote: Total 5759 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (5759/5759), 3.52 MiB | 707.00 KiB/s, done.
Resolving deltas: 100% (3338/3338), done.
Checking connectivity... done.
* Getting dynamo (git://github.com/elixir-lang/dynamo.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamoApp/deps/dynamo'...
remote: Reusing existing pack: 5750, done.
remote: Counting objects: 60, done.
remote: Compressing objects: 100% (56/56), done.
remote: Total 5810 (delta 9), reused 0 (delta 0)
Receiving objects: 100% (5810/5810), 1.29 MiB | 918.00 KiB/s, done.
Resolving deltas: 100% (2323/2323), done.
Checking connectivity... done.
* Getting mime (git://github.com/dynamo/mime.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamoApp/deps/mime'...
remote: Counting objects: 46, done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 46 (delta 14), reused 34 (delta 10)
Receiving objects: 100% (46/46), 29.10 KiB | 0 bytes/s, done.
Resolving deltas: 100% (14/14), done.
Checking connectivity... done.
* Getting cowlib (git://github.com/extend/cowlib.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamoApp/deps/cowlib'...
remote: Reusing existing pack: 78, done.
remote: Total 78 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (78/78), 51.52 KiB | 0 bytes/s, done.
Resolving deltas: 100% (39/39), done.
Checking connectivity... done.
* Getting ranch (git://github.com/extend/ranch.git)
Cloning into '/Users/evan.frolich/Sites/elixir/dynamoApp/deps/ranch'...
remote: Reusing existing pack: 799, done.
remote: Total 799 (delta 0), reused 0 (delta 0)
Receiving objects: 100% (799/799), 253.53 KiB | 0 bytes/s, done.
Resolving deltas: 100% (461/461), done.
Checking connectivity... done.
* Compiling ranch
==> ranch (compile)
Compiled src/ranch_protocol.erl
Compiled src/ranch_transport.erl
Compiled src/ranch_acceptor.erl
Compiled src/ranch_acceptors_sup.erl
Compiled src/ranch_app.erl
Compiled src/ranch_listener_sup.erl
Compiled src/ranch.erl
Compiled src/ranch_conns_sup.erl
Compiled src/ranch_server.erl
Compiled src/ranch_sup.erl
Compiled src/ranch_tcp.erl
Compiled src/ranch_ssl.erl
* Compiling cowlib
==> cowlib (compile)
Compiled src/cow_cookie.erl
Compiled src/cow_http.erl
Compiled src/cow_date.erl
Compiled src/cow_qs.erl
Compiled src/cow_spdy.erl
Compiled src/cow_mimetypes.erl
* Compiling cowboy
==> cowboy (compile)
Compiled src/cowboy_http_handler.erl
Compiled src/cowboy_loop_handler.erl
Compiled src/cowboy_middleware.erl
Compiled src/cowboy_sub_protocol.erl
Compiled src/cowboy_websocket_handler.erl
Compiled src/cowboy_app.erl
Compiled src/cowboy.erl
Compiled src/cowboy_bstr.erl
Compiled src/cowboy_clock.erl
Compiled src/cowboy_client.erl
Compiled src/cowboy_handler.erl
Compiled src/cowboy_multipart.erl
Compiled src/cowboy_protocol.erl
Compiled src/cowboy_http.erl
Compiled src/cowboy_router.erl
Compiled src/cowboy_spdy.erl
Compiled src/cowboy_static.erl
Compiled src/cowboy_rest.erl
Compiled src/cowboy_sup.erl
Compiled src/cowboy_req.erl
Compiled src/cowboy_websocket.erl
* Compiling mime
Compiled lib/mime.ex
== Compilation error on file lib/mime/types.ex ==
could not compile dependency mime, mix compile failed. You can recompile this dependency with `mix deps.compile mime` or update it with `mix deps.update mime`
** (UndefinedFunctionError) undefined function: String.match?/2
    (elixir) String.match?("# This is a comment. I love comments.\t\t    -*- indent-tabs-mode: t -*-\n", %r"^[#\n]")
    lib/mime/types.ex:10: :elixir_compiler_1."-__MODULE__/1-fun-0-"/2
    (elixir) lib/enum.ex:1139: Enum."-reduce/3-fun-0-"/3
    (elixir) lib/stream.ex:994: Stream.do_resource/5
    (elixir) lib/enum.ex:1138: Enum.reduce/3
    lib/mime/types.ex:9: (module)
```

**Comment by devinus** [comment]
@evan108108 Add tag: "elixir-0.12.2" to your mix.exs like so:

``` elixir
{ :dynamo, "~> 0.1.0-dev", github: "elixir-lang/dynamo", tag: "elixir-0.12.2" }
```

**Comment by evan108108** [comment]
@devinus Sorry for my ignorance but I am new to Elixir and Dynamo. I am not sure exactly where to add this. Here is my current mix.exs:

``` elixir
defmodule Dynamo.Mixfile do
  use Mix.Project

  def project do
    [ app: :dynamo,
      elixir: "~> 0.12.0",
      version: "0.1.0-dev",
      name: "Dynamo",
      source_url: "https://github.com/elixir-lang/dynamo",
      tag: "elixir-0.12.2",
      deps: deps(Mix.env) ]
  end

  def deps(:prod) do
      [ { :mimetypes, github: "spawngrid/mimetypes", override: true },
      { :cowboy,  github: "extend/cowboy", optional: true } ]
  end

  def deps(:docs) do
    deps(:prod) ++
      [ { :ex_doc, github: "elixir-lang/ex_doc" } ]
  end

  def deps(_) do
    deps(:prod) ++
      [ { :hackney, github: "benoitc/hackney", tag: "0.10.1" } ]
  end

  def application do
    [ applications: [:crypto, :mimetypes],
      env: [under_test: nil],
      mod: { Dynamo.App, [] } ]
  end
end
``
```

**Comment by devinus** [comment]
@evan108108 It's not ignorance, it could be documented more clearly. You need to add it to your _project's_ mix.exs, the one created when you used `mix dynamo`

**Comment by evan108108** [comment]
@devinus Of Course that makes more sense! Now its working!!! Thank you very much for being so kind. :)
