### ISSUE TITLE
Bug in QueryParser

### ISSUE THREAD

**Issue by kalloc** [dynamo/dynamo#214]
Hi.
I found bug in QueryParser

```
Dynamo.Connection.QueryParser.parse("1=1&n=2&n[]=3&n[]=4")
```

Produced

```
** (Dynamo.Connection.QueryParser.ParseError) expected string at n
    (dynamo) lib/dynamo/connection/query_parser.ex:72: anonymous fn/2 in Dynamo.Connection.Query
Parser.assign_parts/3
    (dynamo) lib/binary/dict.ex:142: Binary.Dict.keyupdate/4
    (dynamo) lib/binary/dict.ex:112: Binary.Dict.update/4
    (elixir) lib/enum.ex:1120: Enum."-reduce/3-lists^foldl/2-0-"/3

```

**Comment by Tonkpils** [comment]
@ybw What would be the expected behavior when parsing that string? 

Using Ruby's `Rack::Utils.parse_nested_query` it raises a similar exception

``` ruby
Rack::Utils.parse_nested_query("a=2&a[]=3")
TypeError: expected Array (got String) for param `a'
```

**Comment by kalloc** [comment]
Yes, may be you are right
