### ISSUE TITLE
Newly created project fails to build

### ISSUE THREAD

**Issue by dvv** [dynamo/dynamo#219]
```
Compiled lib/foo.ex
== Compilation error on file lib/foo/dynamo.ex ==
** (ArgumentError) argument error
    :erlang.function_exported({Dynamo.Filters.Exceptions, Dynamo.Filters.Exceptions.Debug}, :service, 2)
    (elixir) lib/kernel.ex:2599: Kernel.function_exported?/3
    (dynamo) lib/dynamo/router/filters.ex:135: Dynamo.Router.Filters.compile_filter/2
    (elixir) lib/enum.ex:1241: Enum."-reduce/3-lists^foldl/2-0-"/3
    (dynamo) lib/dynamo/router/filters.ex:75: Dynamo.Router.Filters."MACRO-__before_compile__"/2
    (dynamo) /home/dvv/projects/DYNAMO/foo/lib/foo/dynamo.ex:1: Dynamo.Router.Filters.__before_compile__/1
    /home/dvv/projects/DYNAMO/foo/lib/foo/dynamo.ex:1: Foo.Dynamo (module)
```

**Comment by devinus** [comment]
@dvv What version of Elixir?

**Comment by dvv** [comment]
master

**Comment by dvv** [comment]
I just tried to follow the installation section of readme

**Comment by dvv** [comment]
Strange that we pass a tuple  `{Dynamo.Filters.Exceptions, Dynamo.Filters.Exceptions.Debug}` instead of "module" (atom?) to `erlang:function_exported/3`...

**Comment by Andy-Richards** [comment]
Same issue for me too using Elixir 0.13.1

**Comment by parroty** [comment]
I think it's related to (3) of https://github.com/dynamo/dynamo/pull/220.  Does this error still occur?

**Comment by stevedomin** [comment]
Should we close this one?
